name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: find folder
      run: ls -a
      
    
    - name: compile
      run: gcc Main.c -o Main.exe
      
    - name: run 
      run: Main.exe
